In [1]:
# genomic traits analysis for the strains used in the experiment

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pprint
sns.set(style="white", context='poster')

In [5]:
import os
dpath = 'trait_gene_annotations'
os.listdir(dpath)

['42003_2022_3184_MOESM4_ESM_select_genomes.xlsx',
 'genetic_traits_table.tsv',
 'genetic_traits_table_filtered.tsv',
 'genomes_annotation_long_format.7z',
 'strain_list.csv']

In [6]:
strains = pd.read_csv(os.path.join(dpath, 'strain_list.csv'))

In [7]:
strains

,Species,GTDB taxonomy,NCBI taxonID,Accession number,Filename
0,Ruegeria pomeroyi DSS-3,d__Bacteria;p__Proteobacteria;c__Alphaproteoba...,246200,GCA_000011965.2,GCA_000011965
1,Pseudoalteromonas haloplanktis TAC125,d__Bacteria;p__Proteobacteria;c__Gammaproteoba...,326442,GCA_000026085.1,GCA_000026085
2,Alteromonas macleodii HOT1A3,d__Bacteria;p__Proteobacteria;c__Gammaproteoba...,529120,2687454166,2687453488
3,Marinobacter adhaerens HP15,d__Bacteria;p__Proteobacteria;c__Gammaproteoba...,225937,650377991,650377991
4,Phaeobacter gallaeciensis DSM 26640,d__Bacteria;p__Proteobacteria;c__Alphaproteoba...,1423144,GCA_000511385.1,GCA_000511385
5,Sulfitobacter pseudonitzschiae strain SMR1,d__Bacteria;p__Proteobacteria;c__Alphaproteoba...,1402135,CeMEB_private,Sulfitobacter_pseudonitzschiae_SMR1

In [15]:
vitamins_df = pd.read_excel(os.path.join(dpath, '42003_2022_3184_MOESM4_ESM_select_genomes.xlsx'), sheet_name='Supp_Data_4', skiprows=3)
vitamins_df.head()

,Unnamed: 0,GFC,Species,Taxon,Filename,B1-synt,B1-trans,B12-synt,B12-trans,B7-synt,B7-trans
0,NaN,1.0,gamma proteobacterium SCGC AAA076-D02,Gammaproteobacteria,2228664052,1,0,0,0,1,0
1,NaN,NaN,gamma proteobacterium SCGC AAA076-F14,Gammaproteobacteria,2236347022,1,0,0,0,1,0
2,NaN,NaN,SAR324 cluster deltaproteobacterium REDSEA-S10_B5,Others,2651870254,0,1,0,0,0,1
3,NaN,2.0,alpha proteobacterium sp. HIMB59,Alphaproteobacteria,2503982041,0,1,0,0,0,1
4,NaN,NaN,alpha proteobacterium SCGC AAA240-E13,Alphaproteobacteria,2236661011,1,0,0,0,0,1

In [14]:
kegg_names_df = pd.read_excel(os.path.join(dpath, '42003_2022_3184_MOESM4_ESM_select_genomes.xlsx'), sheet_name='Supp_Data_6', skiprows=3)
kegg_names_df.head()

,Unnamed: 0,ID,Description,Frequency,Interaction traits,KEGG hierarchy,...6,Notes,Reference
0,NaN,M00001,"M00001 Glycolysis (Embden-Meyerhof pathway), ...",0.484144,NaN,Carbohydrate metabolism,Central carbohydrate metabolism,NaN,NaN
1,NaN,M00002,"M00002 Glycolysis, core module involving thre...",0.995772,NaN,Carbohydrate metabolism,Central carbohydrate metabolism,NaN,NaN
2,NaN,M00003,"M00003 Gluconeogenesis, oxaloacetate => fruct...",0.813953,NaN,Carbohydrate metabolism,Central carbohydrate metabolism,NaN,NaN
3,NaN,M00004,M00004 Pentose phosphate pathway (Pentose pho...,0.773784,NaN,Carbohydrate metabolism,Central carbohydrate metabolism,NaN,NaN
4,NaN,M00005,"M00005 PRPP biosynthesis, ribose 5P => PRPP [...",1.000000,NaN,Carbohydrate metabolism,Central carbohydrate metabolism,NaN,NaN

In [13]:
traits_df = pd.read_csv(os.path.join(dpath, 'genetic_traits_table.tsv'), sep='\t')
traits_df.head()

,filename,M00001,M00002,M00003,M00004,M00005,M00006,M00007,M00008,M00009,...,pvuABCDE,pvsABCDE,Auxin.TAM,Auxin.Ipyr,Auxin.IAN,Auxin.IAM,DMSP_demethylation,DMSP_cleavage,DHPS_catabolism,Taurine_in_TCA
0,2228664052.fna,0,1,1,0,1,0,1,0,0,...,0,0,1,1,0,0,1,0,1,0
1,2236347022.fna,0,1,1,0,1,1,1,0,0,...,0,0,0,1,0,0,1,0,1,1
2,2236661011.fna,0,0,0,0,1,0,1,0,1,...,0,0,1,0,0,0,1,0,1,0
3,2501651206.fna,1,1,1,0,1,0,1,0,0,...,1,0,1,1,0,0,0,0,0,0
4,2501651207.fna,0,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0

In [17]:
traits_df['filename'] = traits_df.filename.str.replace('.fna', '', regex=False)